export const EVENTS = {
    IMAGE_CHANGE : "IMAGE_CHANGE",
    FORCE_UPDATE : "FORCE_UPDATE",
    DIMENSION_CHANGE : "DIMENSION_CHANGE",
    CHANNEL_CHANGE : "CHANNEL_CHANGE",
    REGIONS_VISIBILITY : "REGIONS_VISIBILITY"
}
